In [108]:
import numpy as np
np.random.seed(123)

random_int = np.random.randint(1,high=1000,size=(20,5))
print("Random List generated:",random_int)

# Q1 What is the average value of first 5 rows (2 decimal places)?

avg_rd1 = random_int[0:5]
print("\nFirst 5 rows are:",avg_rd1)
print("\nAverage value of first 5 rows are:",avg_rd1.mean())

# Q2 What is the average value of the second element in each of the list (2 decimal places)?

avg_elm = random_int[:,1:2]
print("\nSecond element from each list are:",avg_elm)
print("\nAverage value of second element from each list are:",avg_elm.mean())



Random List generated: [[511 366 383 323 989]
 [ 99 743  18 596 107]
 [124 570 215 738  97]
 [114 639  48  74 545]
 [943 225 112 410 340]
 [847 254 421 609 209]
 [ 69 818 824 452   3]
 [341  40 323 597 560]
 [505 958 177 136 874]
 [100 381 861 181 359]
 [866 214 631 863 412]
 [291 994 589 681 900]
 [107 838 577 844 419]
 [827 395 791 718 147]
 [485 272 412 766 159]
 [181 583 366 372 155]
 [721 391 783 256 245]
 [360 972 951 968 130]
 [556 187 358 696 538]
 [435 981 825 306 781]]

First 5 rows are: [[511 366 383 323 989]
 [ 99 743  18 596 107]
 [124 570 215 738  97]
 [114 639  48  74 545]
 [943 225 112 410 340]]

Average value of first 5 rows are: 373.16

Second element from each list are: [[366]
 [743]
 [570]
 [639]
 [225]
 [254]
 [818]
 [ 40]
 [958]
 [381]
 [214]
 [994]
 [838]
 [395]
 [272]
 [583]
 [391]
 [972]
 [187]
 [981]]

Average value of second element from each list are: 541.05


In [109]:
import pandas as pd
data = pd.read_html("https://gist.github.com/seankross/a412dfbd88b3db70b74b")
mtcars_df = data[0]

# Q3 Get the names of car(s) with highest power to displacement ratio.



# Q4 How many cars have 4 cylinder and 4 gears?

countcars = mtcars_df[(mtcars_df['cyl'] == 4) & (mtcars_df['gear'] == 4)]

print (countcars)

print ("\nTotal number of cars having 4 cylinder and 4 gears are:", countcars.model.count())


    Unnamed: 0           model   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
2          NaN      Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   
7          NaN       Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   
8          NaN        Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   
17         NaN        Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   
18         NaN     Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   
19         NaN  Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   
25         NaN       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   
31         NaN      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   

    am  gear  carb  
2    1     4     1  
7    0     4     2  
8    0     4     2  
17   1     4     1  
18   1     4     2  
19   1     4     1  
25   1     4     1  
31   1     4     2  

Total number of cars having 4 cylinder and 4 gears are: 8


In [110]:
# Write a python program to count the number of occurrences of all vowels present in a string

Str1 = input("Enter a string: ")

val = Str1.count('a') + Str1.count('e') + Str1.count('i') + Str1.count('o') + Str1.count('u') + Str1.count('A') + Str1.count('E') + Str1.count('I') + Str1.count('O') + Str1.count('U')
        
print("Number of Vowel present in",Str1, "are: ", val)
    

Enter a string: AccelerateAI
Number of Vowel present in AccelerateAI are:  7
